import { FlowCompileError } from "whatsapp-flow-core";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { FlowsAppConfig } from "whatsapp-flow-tsx";
import { type LockEntry, type Lockfile, readLock } from "./lockfile.ts";
import { loadProject } from "./project.ts";

/** Locked Meta asset ids for one WABA, split by kind. Keys are the full Meta
 * asset name (template `@language` suffix stripped). */
export interface IdMap {
  flows: Record<string, string>;
  templates: Record<string, string>;
}

function sortKeys(obj: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => a.localeCompare(b)));
}

/** Resolve which WABA section to read from the lock for the current env. */
export function resolveLockedWaba(app: FlowsAppConfig, lock: Lockfile): string {
  const id = app.waba?.id?.trim();
  if (!id) {
    throw new FlowCompileError(
      "No WABA id. Set `waba: { id: process.env.WHATSAPP_WABA_ID! }` in flows.config.ts " +
        "and export WHATSAPP_WABA_ID in your env file.",
    );
  }
  if (!lock.wabas[id]) {
    const known = Object.keys(lock.wabas).join(", ") || "(none)";
    throw new FlowCompileError(
      `No locked assets for WABA ${id}. Run \`whatsapp-flow push\` first. Locked WABAs: ${known}.`,
    );
  }
  return id;
}

/** Turn one WABA's lock section into a { flows, templates } id map. Template
 * keys (`tpl:<name>@<lang>`) collapse to the base name; legacy entries with no
 * `kind` are flows. */
export function buildIdMap(section: Record<string, LockEntry>): IdMap {
  const flows: Record<string, string> = {};
  const templates: Record<string, string> = {};
  for (const [key, entry] of Object.entries(section)) {
    if (entry.kind === "template") {
      const base = key.replace(/^tpl:/, "").replace(/@[^@]+$/, "");
      if (base in templates) {
        throw new FlowCompileError(
          `Template "${base}" is locked in multiple languages; can't build a unique id map.`,
        );
      }
      templates[base] = entry.id;
    } else {
      flows[key] = entry.id;
    }
  }
  return { flows: sortKeys(flows), templates: sortKeys(templates) };
}

/** A typed `export const WHATSAPP_FLOWS = {...} as const` module. */
export function renderModule(map: IdMap, wabaId: string): string {
  return [
    "// AUTO-GENERATED by `whatsapp-flow push`. Do not edit by hand.",
    `// Meta asset ids for WABA ${wabaId}.`,
    "",
    `export const WHATSAPP_WABA_ID = ${JSON.stringify(wabaId)};`,
    "",
    `export const WHATSAPP_FLOWS = ${JSON.stringify(map.flows, null, 2)} as const;`,
    `export const WHATSAPP_TEMPLATES = ${JSON.stringify(map.templates, null, 2)} as const;`,
    "",
    "export type WhatsappFlows = typeof WHATSAPP_FLOWS;",
    "export type WhatsappTemplates = typeof WHATSAPP_TEMPLATES;",
    "",
  ].join("\n");
}

/** A single `WHATSAPP_FLOWS='{...}'` line for piping into a .env file. */
export function renderEnvLine(map: IdMap): string {
  return `WHATSAPP_FLOWS='${JSON.stringify(map)}'`;
}

export interface IdsOptions {
  env?: boolean;
  out?: string;
}

/** Read flows.lock.json and emit the locked Meta asset ids for the current
 * env's WABA: a typed TS module (--out), a .env line (--env), or pretty JSON
 * (default). `push` writes the default module automatically; this command is
 * for custom paths or env-line piping. */
export async function runIds(flowsDir: string, opts: IdsOptions = {}): Promise<void> {
  const project = await loadProject(flowsDir);
  const lock = await readLock(project.dir);
  const wabaId = resolveLockedWaba(project.app, lock);
  const map = buildIdMap(lock.wabas[wabaId]!);

  if (opts.out) {
    const dest = path.resolve(opts.out);
    await mkdir(path.dirname(dest), { recursive: true });
    await writeFile(dest, renderModule(map, wabaId), "utf8");
    const count = Object.keys(map.flows).length + Object.keys(map.templates).length;
    console.log(`✓ Wrote ${count} id(s) for WABA ${wabaId} to ${path.relative(process.cwd(), dest)}`);
  }
  if (opts.env) console.log(renderEnvLine(map));
  if (!opts.out && !opts.env) console.log(JSON.stringify(map, null, 2));
}
