import { FlowCompileError } from "whatsapp-flow-core";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { type LockEntry, type Lockfile, readLock } from "./lockfile.ts";
import { loadProject } from "./project.ts";

/** Locked Meta asset ids for one env, split by kind. Keys are the full Meta
 * asset name (template `@language` suffix stripped). */
export interface EnvIdMap {
  flows: Record<string, string>;
  templates: Record<string, string>;
}

/** Locked ids across every env, plus each env's WABA id. */
export interface AllEnvIdMaps {
  /** env -> WABA id */
  wabas: Record<string, string>;
  /** env -> (flow name -> id) */
  flows: Record<string, Record<string, string>>;
  /** env -> (template name -> id) */
  templates: Record<string, Record<string, string>>;
}

function sortKeys(obj: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => a.localeCompare(b)));
}

/** Turn one env's lock assets into a { flows, templates } id map. Template keys
 * (`tpl:<name>@<lang>`) collapse to the base name; legacy entries with no `kind`
 * are flows. */
export function buildIdMap(assets: Record<string, LockEntry>): EnvIdMap {
  const flows: Record<string, string> = {};
  const templates: Record<string, string> = {};
  for (const [key, entry] of Object.entries(assets)) {
    if (entry.kind === "template") {
      const base = key.replace(/^tpl:/, "").replace(/@[^@]+$/, "");
      if (base in templates) {
        throw new FlowCompileError(
          `Template "${base}" is locked in multiple languages; can't build a unique id map.`,
        );
      }
      templates[base] = entry.id;
    } else {
      flows[key] = entry.id;
    }
  }
  return { flows: sortKeys(flows), templates: sortKeys(templates) };
}

/** Build per-env id maps for every locked env, sorted by env name. */
export function buildAllEnvIdMaps(lock: Lockfile): AllEnvIdMaps {
  const wabas: Record<string, string> = {};
  const flows: Record<string, Record<string, string>> = {};
  const templates: Record<string, Record<string, string>> = {};
  for (const env of Object.keys(lock.envs).sort()) {
    const { wabaId, assets } = lock.envs[env]!;
    const map = buildIdMap(assets);
    wabas[env] = wabaId;
    flows[env] = map.flows;
    templates[env] = map.templates;
  }
  return { wabas, flows, templates };
}

/** A typed all-envs ids module with `flowId()` / `templateId()` helpers. The
 * helpers default the env to `process.env.WHATSAPP_ENV` (falling back to
 * `defaultEnv`), evaluated per call, and throw loudly on an unknown env or name. */
export function renderModule(maps: AllEnvIdMaps, defaultEnv = "dev"): string {
  const def = JSON.stringify(defaultEnv);
  return [
    "// AUTO-GENERATED by `whatsapp-flow push`. Do not edit by hand.",
    "// Meta asset ids per environment.",
    "",
    `export const WHATSAPP_WABAS = ${JSON.stringify(maps.wabas, null, 2)} as const;`,
    "",
    `export const WHATSAPP_FLOWS = ${JSON.stringify(maps.flows, null, 2)} as const;`,
    `export const WHATSAPP_TEMPLATES = ${JSON.stringify(maps.templates, null, 2)} as const;`,
    "",
    "export type WhatsappEnv = keyof typeof WHATSAPP_FLOWS;",
    "export type FlowName = keyof (typeof WHATSAPP_FLOWS)[WhatsappEnv];",
    "export type TemplateName = keyof (typeof WHATSAPP_TEMPLATES)[WhatsappEnv];",
    "",
    `function currentEnv(): WhatsappEnv {`,
    `  return (process.env.WHATSAPP_ENV ?? ${def}) as WhatsappEnv;`,
    "}",
    "",
    "export function flowId(name: FlowName, env: WhatsappEnv = currentEnv()): string {",
    "  const map = WHATSAPP_FLOWS[env] as Record<string, string> | undefined;",
    '  if (!map) throw new Error(`Unknown env "${env}"`);',
    "  const id = map[name];",
    '  if (!id) throw new Error(`No locked flow id for "${name}" in env "${env}"`);',
    "  return id;",
    "}",
    "",
    "export function templateId(name: TemplateName, env: WhatsappEnv = currentEnv()): string {",
    "  const map = WHATSAPP_TEMPLATES[env] as Record<string, string> | undefined;",
    '  if (!map) throw new Error(`Unknown env "${env}"`);',
    "  const id = map[name];",
    '  if (!id) throw new Error(`No locked template id for "${name}" in env "${env}"`);',
    "  return id;",
    "}",
    "",
  ].join("\n");
}

/** A single `WHATSAPP_FLOWS='{...}'` line for piping into a .env file. */
export function renderEnvLine(map: EnvIdMap): string {
  return `WHATSAPP_FLOWS='${JSON.stringify(map)}'`;
}

export interface IdsOptions {
  env?: string;
  envLine?: boolean;
  out?: string;
}

/** Read flows.lock.json and emit locked Meta asset ids. `--out` writes the typed
 * all-envs TS module; `--env-line` prints the resolved env's `WHATSAPP_FLOWS='…'`
 * line; otherwise the resolved env's ids print as JSON. `push` writes the default
 * module automatically; this command is for custom paths or env-line piping. */
export async function runIds(flowsDir?: string, opts: IdsOptions = {}): Promise<void> {
  const project = await loadProject(flowsDir, { env: opts.env });
  const lock = await readLock(project.dir);

  if (opts.out) {
    const dest = path.resolve(opts.out);
    await mkdir(path.dirname(dest), { recursive: true });
    const all = buildAllEnvIdMaps(lock);
    await writeFile(dest, renderModule(all, project.app.defaultEnv), "utf8");
    const envCount = Object.keys(all.wabas).length;
    console.log(`✓ Wrote ids for ${envCount} env(s) to ${path.relative(process.cwd(), dest)}`);
  }

  if (opts.envLine || !opts.out) {
    const section = lock.envs[project.env];
    if (!section) {
      const known = Object.keys(lock.envs).join(", ") || "(none)";
      throw new FlowCompileError(
        `No locked assets for env "${project.env}". Run \`whatsapp-flow push --env ${project.env}\` first. Locked envs: ${known}.`,
      );
    }
    const map = buildIdMap(section.assets);
    if (opts.envLine) console.log(renderEnvLine(map));
    else if (!opts.out) console.log(JSON.stringify(map, null, 2));
  }
}
