import { FlowCompileError } from "whatsapp-flow-core";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { FlowsAppConfig } from "whatsapp-flow-tsx";
import { type LockEntry, type Lockfile, readLock } from "./lockfile.ts";
import { loadProject } from "./project.ts";

/** Locked Meta asset ids for one WABA, split by kind. Keys are the full Meta
 * asset name (template `@language` suffix stripped). */
export interface IdMap {
  flows: Record<string, string>;
  templates: Record<string, string>;
}

function sortKeys(obj: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => a.localeCompare(b)));
}

/** Pick which WABA's ids to emit. Defaults to the app `defaultWaba`, else "dev"
 * if locked, else the sole locked WABA. Validates against what's in the lock. */
export function selectWaba(
  app: FlowsAppConfig,
  lock: Lockfile,
  wabaArg: string | undefined,
): string {
  const locked = Object.keys(lock.wabas);
  if (locked.length === 0) {
    throw new FlowCompileError(
      "No locked assets. Run `whatsapp-flow push` first to populate flows.lock.json.",
    );
  }
  if (wabaArg === "both") {
    throw new FlowCompileError(
      "`ids` emits one WABA's ids (they differ per WABA); --waba both isn't supported. Pick one.",
    );
  }
  const pick =
    wabaArg ??
    app.defaultWaba ??
    (locked.includes("dev") ? "dev" : locked.length === 1 ? locked[0] : undefined);
  if (!pick) {
    throw new FlowCompileError(
      `Multiple WABAs in the lockfile (${locked.join(", ")}); pass --waba <label>.`,
    );
  }
  if (!lock.wabas[pick]) {
    throw new FlowCompileError(
      `No locked assets for WABA "${pick}". Locked: ${locked.join(", ") || "(none)"}.`,
    );
  }
  return pick;
}

/** Turn one WABA's lock section into a { flows, templates } id map. Template
 * keys (`tpl:<name>@<lang>`) collapse to the base name; legacy entries with no
 * `kind` are flows. */
export function buildIdMap(section: Record<string, LockEntry>): IdMap {
  const flows: Record<string, string> = {};
  const templates: Record<string, string> = {};
  for (const [key, entry] of Object.entries(section)) {
    if (entry.kind === "template") {
      const base = key.replace(/^tpl:/, "").replace(/@[^@]+$/, "");
      if (base in templates) {
        throw new FlowCompileError(
          `Template "${base}" is locked in multiple languages; can't build a unique id map.`,
        );
      }
      templates[base] = entry.id;
    } else {
      flows[key] = entry.id;
    }
  }
  return { flows: sortKeys(flows), templates: sortKeys(templates) };
}

/** A typed `export const WHATSAPP_FLOWS = {...} as const` module. */
export function renderModule(map: IdMap, label: string): string {
  return [
    "// AUTO-GENERATED by `whatsapp-flow ids`. Do not edit by hand.",
    `// Meta asset ids for WABA "${label}". Regenerate after \`whatsapp-flow push\`.`,
    "",
    `export const WHATSAPP_FLOWS = ${JSON.stringify(map, null, 2)} as const;`,
    "",
    "export type WhatsappFlows = typeof WHATSAPP_FLOWS;",
    "",
  ].join("\n");
}

/** A single `WHATSAPP_FLOWS='{...}'` line for piping into a .env file. */
export function renderEnvLine(map: IdMap): string {
  return `WHATSAPP_FLOWS='${JSON.stringify(map)}'`;
}

export interface IdsOptions {
  waba?: string;
  env?: boolean;
  out?: string;
}

/** Read flows.lock.json and emit the locked Meta asset ids for one WABA: a
 * typed TS module (--out), a .env line (--env), or pretty JSON (default). */
export async function runIds(flowsDir: string, opts: IdsOptions = {}): Promise<void> {
  const project = await loadProject(flowsDir);
  const lock = await readLock(project.dir);
  const label = selectWaba(project.app, lock, opts.waba);
  const map = buildIdMap(lock.wabas[label]!);

  if (opts.out) {
    const dest = path.resolve(opts.out);
    await mkdir(path.dirname(dest), { recursive: true });
    await writeFile(dest, renderModule(map, label), "utf8");
    const count = Object.keys(map.flows).length + Object.keys(map.templates).length;
    console.log(
      `✓ Wrote ${count} id(s) for WABA "${label}" to ${path.relative(process.cwd(), dest)}`,
    );
  }
  if (opts.env) console.log(renderEnvLine(map));
  if (!opts.out && !opts.env) console.log(JSON.stringify(map, null, 2));
}
